### ISSUE TITLE
Middleware makes 2X calls to all the views!!

### ISSUE THREAD

**Issue by chachra** [descope/django-descope#134]
Big bug and a pretty frustrating one..

https://github.com/descope/django-descope/blob/main/django_descope/middleware.py#L17

All views get called 2X if using the descope middleware.

**Comment by meirwah** [comment]
@chachra thanks for reporting, looking at this ASAP

**Comment by omercnet** [comment]
hi @chachra, I'm afraid I'm unable to reproduce 

Could you please share more information about your app?
a `pip freeze` would be helpful

perhaps logs showing the double calls

**Comment by chachra** [comment]
See revised code below. If user is logged in get_response is being called twice. See commented out line below.

`class DescopeMiddleware:
    _auth = DescopeAuthentication()

    def __init__(self, get_response: HttpResponse = None):
        self.get_response = get_response

    def __call__(self, request: HttpRequest):
        # response: HttpResponse = self.get_response(request)

        user = self._auth.authenticate(request)
        if user:
            login(request, user)

        response: HttpResponse = self.get_response(request)

        return response
`

**Comment by chachra** [comment]
Thanks for fixing folks! Didn't mean to scare anyone... I just lost 2 days of sleep having never seen such behavior in Django.

Sorry if I made anyone work on the weekend! Cheers.
