### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by eric-prog** [descope/django-descope#144]
Upon doing `pip3 install django-descope.`

I get the error:
`ModuleNotFoundError: No module named 'debug_toolbar'`

I resolved by doing (https://bobbyhadz.com/blog/python-no-module-named-debug-toolbar):
`pip3 install django-debug-toolbar`

Maybe missing dependency?

**Comment by omercnet** [comment]
Hi @eric-prog I was unable to reproduce this.

the debug_toolbar is used only in the example app, and not in the published code
is there a chance you tried running the example app and not your own django project?

if you'd like to use the sample app you should install all the project dependencies, it's best to use poetry to install the local dev environment
