### ISSUE TITLE
How to Use with DescopeClient?

### ISSUE THREAD

**Issue by benjamin-kirkbride** [descope/django-descope#152]
It's not entirely clear to me what to do once the user is logged in using `django-descope`. For instance, looking at: https://github.com/descope/python-sdk/blob/main/samples/access_key_sample_app.py as an example, how would one do:

```python
            permission_name = "TestPermission"
            permission_presented = descope_client.validate_permissions(
                jwt_response, [permission_name]
            )
            logging.info(
                f"{permission_name} presented on the jwt: [{permission_presented}]"
            )
            role_name = "TestRole"
            role_presented = descope_client.validate_roles(jwt_response, [role_name])
            logging.info(f"{role_name} presented 
```

using `django-descope`? Should I be using the Descope Python SDK directly, and use `DescopeClient` separately from `django-descope`, or is there a better way?

**Comment by omercnet** [comment]
hi @benjamin-kirkbride roles are currently stored on the DescopeUser model in a private property `_roles` but we can definitely expose it to make your life easier

let me work on a fix to expose more user attributes through DescopeUser model

**Comment by benjamin-kirkbride** [comment]
I guess I'm kind of asking more broadly functionality `descope-django` is expected (intended?) to enable compared to the Python SDK. Should I be able to get and set all attributes, such as roles, permissions, attributes (including custom), tenants, etc, or should I also use the SDK with it?

should `descope-django` expose a  `DescopeClient` somehow? or is there an example of how I would use the session/user/jwt with the SDK?

Hopefully these questions make sense.

**Comment by omercnet** [comment]
that makes total sense, ideally having the client exposed is great, but I think it'll be useful to make the information that we already fetch available for you in a Django way

I'll add all the relevant user information on the `DescopeUser` and expose the client in a way that's easy to use for other non-traditional use cases (like management api)

let me also consult internally with the team and make sure this is aligned with all our other SDKs and framework plugins

**Comment by benjamin-kirkbride** [comment]
Sounds great!

Would modifying those attributes on the model be something that's supported? Like it would update on the Descope back-end as well? I am guessing not, because I would see a ton of edge cases cropping up there.

**Comment by omercnet** [comment]
That would require the use of the management api which is definitely possible

Let's start with read first and then write :)

**Comment by benjamin-kirkbride** [comment]
Yeah adding some more attributes to the model + making the DescopeClient accessible I think will cover everything for now.

**Comment by omercnet** [comment]
hi @benjamin-kirkbride take a look at https://github.com/descope/django-descope/pull/153
I modified the role validation for `is_superuser` to use the SDK itself so you can see an example of how to use it

the `session` attribute now holds all the session information for you to access, and the `token` is the actual jwt if you need it for anything extra

**Comment by benjamin-kirkbride** [comment]
Thanks for your work on this @omercnet, I have switched to use the `exposedescope` branch and played around a bit.

I am currently getting this error:


```python
dev-retrieve-front-end-1  | [2023-06-11 23:23:58 +0000] [67] [DEBUG] GET /
dev-retrieve-front-end-1  | Validating (and refreshing) Descope session
dev-retrieve-front-end-1  | Starting new HTTPS connection (1): api.descope.com:443
dev-retrieve-front-end-1  | https://api.descope.com:443 "POST /v1/auth/refresh HTTP/1.1" 200 None
dev-retrieve-front-end-1  | Internal Server Error: /
dev-retrieve-front-end-1  | Traceback (most recent call last):
dev-retrieve-front-end-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
dev-retrieve-front-end-1  |     response = get_response(request)
dev-retrieve-front-end-1  |                ^^^^^^^^^^^^^^^^^^^^^
dev-retrieve-front-end-1  |   File "/usr/local/lib/python3.11/site-packages/django_descope/middleware.py", line 18, in __call__
dev-retrieve-front-end-1  |     user = self._auth.authenticate(request)
dev-retrieve-front-end-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dev-retrieve-front-end-1  |   File "/usr/local/lib/python3.11/site-packages/django_descope/authentication.py", line 47, in authenticate
dev-retrieve-front-end-1  |     return self.get_user(request, validated_session, refresh)
dev-retrieve-front-end-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dev-retrieve-front-end-1  |   File "/usr/local/lib/python3.11/site-packages/django_descope/authentication.py", line 53, in get_user
dev-retrieve-front-end-1  |     user.sync(session, refresh)
dev-retrieve-front-end-1  |   File "/usr/local/lib/python3.11/site-packages/django_descope/models.py", line 23, in sync
dev-retrieve-front-end-1  |     self.token = self.session["jwt"]
dev-retrieve-front-end-1  |                  ~~~~~~~~~~~~^^^^^^^
dev-retrieve-front-end-1  | KeyError: 'jwt'
```

Working through that now.

**Comment by benjamin-kirkbride** [comment]
Seems like [this](https://github.com/descope/django-descope/pull/153/commits/48fb23269de7fc77e1f040944d16a16f9f624020#diff-1c9727e783d627585ee1da58950fdc4675ef635f27e77a53fdd99c88299e64b1R23) should use the `get` method?

**Comment by benjamin-kirkbride** [comment]
I believed this fixes it, based on some quick testing. Seems like when the session expires (almost certainly not the right terms) the subscription method fails.

See: https://github.com/benjamin-kirkbride/django-descope/commit/ee6adbc65c4c2249458a963092b7652ec910cdf8

I would make a PR, but probably not worth it given how minor it is. Also not sure what the CLA situation is

**Comment by benjamin-kirkbride** [comment]
After playing around a bit more, I believe this is what is intended?

```python
class Permissions(View):
    def get(self, request: HttpRequest):
        logger.info("Permissions view called")

        return JsonResponse(
            request.user.descope.mgmt.permission.load_all(),
            json_dumps_params={"indent": 2},
        )
```

It feels a bit.. odd to me to expose the `DescopeClient` this way, but maybe I'm not thinking about it or using it the way that was intended?

**Comment by omercnet** [comment]
thanks for the feedback @benjamin-kirkbride I pushed another update moving the descope client to top so you can reuse it anywhere with `from django_descope import descope_client`

give it a try?

**Comment by benjamin-kirkbride** [comment]
:raised_hands:
