### ISSUE TITLE
Customization of User Creation Process

### ISSUE THREAD

**Issue by Cleptomania** [descope/django-descope#172]
## The Scenario

Given that I have a custom user model, and an associated model like so:

```py
from django.contrib.auth.models import AbstractBaseUser
from django.db import models

class Account(models.Model):
    name = models.CharField(max_length=200)
    descope_tenant = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name


class User(AbstractBaseUser):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
```

This creates a `User` model, with a non-nullable field relating it to the `Account` model, meaning that on creation of a `User`, an account MUST be provided. In my scenario, an `Account` is synonymous with a Descope tenant, and it stores the descope tenant ID.

This association can easily be created by getting the tenant the user belongs to(in this scenario, a user could never be assigned to more than one tenant) during the Django user creation and determining the `Account` for it, and providing that to the foreign key on the user.

## The Problem

As it stands, I don't see a way to customize the user creation process within django-descope. The Django user is created during the `get_user` function in django-descope with the `get_or_create` function and is just passed the username.

## Solutions

One possible solution might be to allow the user to define a callable(maybe via Django's `settings.py` or some function to register it?) which would get called from this function that is expected to work the same as the existing `get_or_create` call. There definitely may be a better solution, this was just one possibility I thought of.

**Comment by omercnet** [comment]
three approaches here:

1. [overriding the save() method](https://docs.djangoproject.com/en/dev/topics/db/models/#overriding-predefined-model-methods) in your model and get the information you need on save
2. use [signals](https://docs.djangoproject.com/en/dev/topics/signals/)

the third approach, in my opinion, is not create a model just for an attribute
since we have the DescopeUser proxy model you can access all of Descope attributes when you reference a user with that proxy model

if you could share an example of how you intended to utilize the Account property I can provide a code sample to implement your use case

**Comment by Cleptomania** [comment]
@omercnet It seems like overriding the save functionality might be what I need, however it's unclear how I should get the user during this.

What I ultimately need is to get the tenants the user belongs to, which I can do with the DescopeClient object but I'm not entirely sure how I would go about getting the active user at this stage of the application.

Basically the Account model will have a `descope_tenant` field on it which is Descope's Tenant ID. Then we can get the tenants a user belongs to and find the account based on that(remember in this scenario a user will only ever be assigned to one tenant). 

The third approach mentioned above is a good idea, and probably sidesteps this issue in other cases, but for my case we need the database to be aware of the relationship between users and accounts because of other systems which will utilize this relationship that don't necessarily have any other reason to interact with descope(reporting, billing, etc).

**Comment by Cleptomania** [comment]
@omercnet This is what I ended up doing in my models and seems to work fine:

```py
class Account(models.Model):
    descope_tenant = models.CharField(max_length=200, unique=True)
    

class User(AbstractUser):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        user_info = descope_client.mgmt.user.load_by_user_id(self.username)
        tenant_id = user_info['user']['userTenants'][0]['tenantId']
        self.account = Account.objects.filter(descope_tenant=tenant_id).first()
        super().save(*args, **kwargs)
```

This overrides Django's `save()` function and grabs the first tenant ID from the Python descope client management interface. I'm not sure if getting the data from the management interface is the best way to do this or not. It seems fine for the moment, but is there a way that you know of to get the actual user session at this point in the application? I'm not aware of any way to get the data from the request unless maybe through some middleware to pull the data out from there and return it back during the save function.

Just curious on your thoughts if this seems like a sensible way to do it or if it would be better to try and not use the management API for it.

**Comment by omercnet** [comment]
@Cleptomania if you must keep a local version of this information in your database to be used by other services, hooking on the `save` method is definitely the way to go.
Just keep in mind that changes outside this mechanism will mean your internal database does not match the state of Descope's database.

As for the use of the management SDK, that is redundant, as all the information about the user already exists on the DescopeUser object

This issue has brought up a few important design issues that we'll address in the next few days - I suggest in the meantime you continue using this solution if it works for you and I'll respond here with an update asap

**Comment by omercnet** [comment]
closing this as issue was resolved, will handle the suggested changes in a dedicated PR
